export function courseHome(curriculum, available) {
 const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
 const modules=[...new Set(curriculum.map(l=>l.module))];
 const time=s=>Math.floor(Math.round(s)/60)+':'+String(Math.round(s)%60).padStart(2,'0');
 const first=available[0],developing=available.length<curriculum.length;
 const videoMinutes=Math.round(available.reduce((sum,lesson)=>sum+lesson.duration,0)/60);
 // Rounded planning scenarios are documented in docs/course/second-review/study-time.md.
 const studyGuide=developing?'':`<section class="study-guide" aria-labelledby="study-guide-heading"><p class="eyebrow">MAKE TIME TO LEARN</p><h2 id="study-guide-heading">Plan your study time.</h2><p>About ${Math.floor(videoMinutes/60)} hours ${videoMinutes%60} minutes of video across ${available.length} lessons. Reading, questions and review are part of the learning too.</p><dl class="study-estimates"><div><dt>About 19 hours</dt><dd>Lessons, written teaching and required questions.</dd></div><div><dt>About 27 hours total</dt><dd>Also includes the diagnostic, three timed practice exams and explanation review.</dd></div><div><dt>About 34 hours total</dt><dd>Also includes later review sessions to help you retain what you learn.</dd></div></dl><p><strong>A suggested pace:</strong> about 2 hours per study day over 3–4 weeks. Revisit missed concepts on later days, and reserve 1 hour 45 minutes without interruptions for each timed practice exam.</p><p class="estimate-note">These are estimates of active study time, not measured learner averages or approved prelicensing hours. Allow extra time for difficult topics.</p></section>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="AMG Maryland life insurance exam preparation with short lessons and required practice."><title>Maryland Life Course · AMG Exam Lab</title><link rel="icon" href="data:,"><link rel="stylesheet" href="/course/shared/home.css"><script src="/course/shared/home.js" defer></script></head><body><a class="skip" href="#lessons">Skip to lessons</a><main>
 <header><a class="brand" href="/course/"><span class="brand-mark"><img src="/course/assets/amg-mark.webp" alt="AMG"></span><span>AMG<br><small>LIFE INSURANCE EXAM LAB</small></span></a><nav aria-label="Course navigation"><a href="/course/assessments/">Practice & review</a><a href="/">Exam center</a><a href="/course/coverage/">Coordinator review</a></nav></header>
 <section class="hero"><p class="eyebrow">MARYLAND LIFE INSURANCE</p><h1>Understand the reason.<br>Apply it with confidence.</h1><p class="intro">Learn one concept at a time, work through realistic situations, and answer the required questions before completing each part.</p><a id="continue-course" class="primary" href="/course/lesson-${first.id}/">Start with Part 1 →</a><p class="study-progress" id="course-progress" role="status">${available.length} lessons available · Progress saves in this browser</p></section>
 <aside class="release-note"><strong>${developing?'Course in development':'Course review edition'}</strong><span>${available.length} of ${curriculum.length} planned lessons available. Licensing-coordinator sign-off is tracked separately; published lessons have completed production checks.</span></aside>
 ${studyGuide}
 <section id="lessons"><div class="section-heading"><p class="eyebrow">YOUR LEARNING PATH</p><h2>Build the knowledge, then practice it.</h2><p>Watch each lesson or use its available written study option. Review explanations and retry missed questions until every required answer is correct.</p></div>
 ${modules.map((name,m)=>{const list=available.filter(l=>l.module===name);if(!list.length)return '';return `<section class="module" aria-labelledby="module-${m}"><h3 id="module-${m}">${esc(name)}</h3><ol class="lesson-list">${list.map(l=>`<li data-lesson="${l.id}" data-version="${l.version||1}" data-answers="${(l.answers||[]).join(',')}"><a href="/course/lesson-${l.id}/"><span class="part">${l.id}</span><span class="lesson-title"><strong>${esc(l.title)}</strong><small>${time(l.duration)} video · ${l.questions} required questions</small></span><span class="lesson-state">Open →</span></a></li>`).join('')}</ol></section>`}).join('')}
 </section>
 ${developing?`<details class="planned"><summary>View the remaining course plan</summary>${modules.map(name=>{const list=curriculum.filter(l=>l.module===name&&!available.some(a=>a.id===l.id));return list.length?`<h3>${esc(name)}</h3><ul>${list.map(l=>`<li>Part ${l.number}: ${esc(l.title)} <small>In development</small></li>`).join('')}</ul>`:''}).join('')}</details>`:''}
 <section class="review"><h2>Practice and review</h2><p>Start with a 32-question diagnostic, then use three independent timed forms and your delayed-review schedule. Keep fresh form scores separate from lesson retries.</p><a href="/course/assessments/">Open practice and review →</a><a href="/">Open legacy drill →</a><a href="/course/coverage/">Open coverage review →</a></section>
 <footer><p>AMG · Life-insurance exam preparation</p><p>Progress is a study record, not a license or a guarantee of an exam result. ${developing?'The complete course and final assessments are still being developed.':'Coordinator approval is recorded separately.'}</p><details><summary>Earlier production sample</summary><a href="/course/term-whole-life.html">Term versus whole life prototype</a><p>This earlier sample uses the previous video format.</p></details></footer>
 </main></body></html>\n`.replace(/^ +$/gm,'');
}
