import {courseHeader,courseFooter,icon} from './course-ui.mjs';
export function courseHome(curriculum, available) {
 const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
 const modules=[...new Set(curriculum.map(l=>l.module))];
 const time=s=>Math.floor(Math.round(s)/60)+':'+String(Math.round(s)%60).padStart(2,'0');
 const first=available[0],videoMinutes=Math.round(available.reduce((sum,l)=>sum+l.duration,0)/60);
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="Your AMG Maryland Life classroom. Watch a lesson, answer its questions and continue learning."><title>Maryland Life · AMG Learning</title><link rel="icon" href="/course/assets/amg-mark.webp"><link rel="stylesheet" href="/course/shared/app.css"><link rel="stylesheet" href="/course/shared/account.css"><script src="/course/shared/account.js" defer></script><link rel="stylesheet" href="/course/shared/home.css"><script src="/course/shared/home.js" defer></script></head><body class="account-loading"><a class="skip" href="#lessons">Skip to lessons</a>${courseHeader('course')}
 <main class="classroom">
 <div class="classroom-heading"><div><p class="eyebrow">YOUR CLASSROOM</p><h1>Maryland Life</h1></div><p class="course-meta"><span>${available.length} lessons</span><span>${icon('clock')}${Math.floor(videoMinutes/60)}h ${videoMinutes%60}m of video</span></p></div>
 <section class="overview" aria-label="Continue your course"><div class="continue-card"><div class="continue-content"><p class="eyebrow" id="continue-label">LET’S GET STARTED</p><p class="continue-kicker" id="continue-meta">PART ${first.id} · ${time(first.duration)} VIDEO</p><h2 id="continue-title">${esc(first.title)}</h2><a id="continue-course" class="primary" href="/course/lesson-${first.id}/"><span>Start lesson</span>${icon('arrow')}</a><p class="continue-note">Watch the video. Answer the questions.</p></div><a class="continue-preview" id="continue-preview-link" href="/course/lesson-${first.id}/" aria-label="Open your next lesson"><img id="continue-poster" src="${esc(first.poster || '/course/assets/amg-mark.webp')}" alt="" width="640" height="360"><span class="preview-play">${icon('play')}</span><span class="preview-time" id="continue-duration">${time(first.duration)}</span></a></div>
 <a class="practice-shortcut" href="/course/assessments/"><span class="practice-symbol">${icon('test')}</span><span class="eyebrow">ON YOUR SCHEDULE</span><h2>Ready to practice?</h2><p>Try a diagnostic or a timed test anytime.</p><span class="shortcut-action">Explore practice tests ${icon('arrow')}</span></a></section>
 <div class="learning-layout"><aside class="chapters" aria-label="Course chapters"><section class="course-progress-panel"><div class="progress-heading"><span>Your progress</span><strong id="course-percent">0%</strong></div><progress id="course-progress-bar" max="${available.length}" value="0" aria-label="Completed lessons"></progress><p id="course-progress" role="status">0 of ${available.length} lessons completed</p></section><p class="eyebrow chapter-label">CHAPTERS</p><nav class="chapter-nav" aria-label="Choose a chapter">${modules.map((name,m)=>{const list=available.filter(l=>l.module===name);return list.length?`<button type="button" class="chapter-button" data-module-button="${m}" aria-pressed="${m===0}" aria-controls="module-panel-${m}"><span class="chapter-number">${String(m+1).padStart(2,'0')}</span><span>${esc(name)}<small data-module-progress="${m}">0 / ${list.length}</small></span>${icon('chevron')}</button>`:''}).join('')}</nav></aside>
 <section id="lessons" class="lesson-browser" aria-label="Course lessons"><div class="browser-tools"><p class="eyebrow" id="browser-label">COURSE CONTENT</p><label class="lesson-search">${icon('search')}<input id="lesson-search" type="search" placeholder="Find a lesson" aria-label="Find a lesson" autocomplete="off"></label></div><div id="lesson-search-status" class="visually-hidden" role="status"></div>
 ${modules.map((name,m)=>{const list=available.filter(l=>l.module===name);if(!list.length)return '';return `<section class="module" data-module="${m}" id="module-panel-${m}" aria-labelledby="module-title-${m}"${m?' hidden':''}><div class="module-heading"><div><p class="module-index">CHAPTER ${String(m+1).padStart(2,'0')}</p><h2 id="module-title-${m}">${esc(name)}</h2></div><span>${list.length} lessons</span></div><ol class="lesson-list">${list.map(l=>`<li data-lesson="${l.id}" data-version="${l.version||1}" data-answers="${(l.answers||[]).join(',')}" data-title="${esc(l.title)}" data-duration="${time(l.duration)}" data-poster="${esc(l.poster||'')}" data-module-index="${m}"><a href="/course/lesson-${l.id}/"><span class="lesson-play">${icon('play')}</span><span class="lesson-title"><span class="lesson-number">LESSON ${l.id}</span><strong>${esc(l.title)}</strong><small>${time(l.duration)} video<span>·</span>${l.questions} questions</small></span><span class="lesson-state">Start</span>${icon('chevron','row-arrow')}</a></li>`).join('')}</ol></section>`}).join('')}
 <div class="search-empty" id="search-empty" hidden><span>${icon('search')}</span><h2>No matching lessons</h2><p>Try a topic like “beneficiary” or “annuity”.</p><button type="button" id="clear-search">Show course chapters</button></div></section></div>
 <details class="course-info"><summary>Course information & study options</summary><div class="course-info-body"><p><strong>Review edition.</strong> Licensing-coordinator approval is recorded separately. Use the same email each time to save progress and report results to your licensing team.</p><p>Complete each video or its transcript alternative, then answer every required question correctly. Practice tests are optional and available anytime. Scores are study feedback, not a guarantee of an exam result.</p><p><strong>Study time:</strong> ${Math.floor(videoMinutes/60)} hours ${videoMinutes%60} minutes of video. Allow extra time for questions, retries and optional review. Each timed practice test allows 105 minutes. These are planning details, not approved education hours.</p><a href="/course/coverage/">Sources & coordinator review</a></div></details>
 ${courseFooter()}</main></body></html>\n`;
}
