import {courseHeader,courseFooter} from './course-ui.mjs';
import {curriculum} from '../docs/course/full-course/curriculum.mjs';
export const escapeHtml = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const esc = escapeHtml;
const durationLabel = duration => {const seconds=Math.round(duration);return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');};
function courseRail(lesson) {
 const modules=[...new Set(curriculum.map(item=>item.module))];
 const active=curriculum.find(item=>item.id===lesson.id)?.module;
 return `<aside class="course-rail" aria-label="Course content"><div class="rail-heading"><h2>Course content</h2><span>${curriculum.length} lessons</span></div><div class="lesson-progress-box"><label for="lesson-progress">This lesson</label><progress id="lesson-progress" max="${lesson.questions}" value="0"></progress><p id="progress-label" aria-live="polite">0 of ${lesson.questions} questions understood</p></div><nav class="module-list" aria-label="Course modules">${modules.map((module,index)=>`<details class="module-group"${module===active?' open':''}><summary><span class="module-number">${String(index+1).padStart(2,'0')}</span><span>${esc(module)}</span><span class="disclosure-chevron" aria-hidden="true"></span></summary><ol>${curriculum.filter(item=>item.module===module).map(item=>`<li><a href="/course/lesson-${item.id}/"${item.id===lesson.id?' aria-current="page"':''}><span class="lesson-number">${item.id}</span><span>${esc(item.title)}</span>${item.id===lesson.id?'<span class="current-lesson-dot" aria-label="Current lesson"></span>':''}</a></li>`).join('')}</ol></details>`).join('')}</nav><a class="rail-test-link" href="/course/assessments/">Practice tests <span aria-hidden="true">↗</span></a><p class="rail-note">Practice is available anytime.</p><p id="save-status">Progress is saved in this browser.</p></aside>`;
}
export function renderLesson({id,number,title,subtitle,duration,questions,narrator='Zoe',previous,next,objectivesHtml,referenceHtml,sourcesHtml,foundation=false}) {
 const lesson={id,number,title,questions};
 const module=curriculum.find(item=>item.id===id)?.module || 'Maryland life';
 const nextLabel=number===60?'Continue to practice tests':next==='/course/'?'Back to course':'Continue to Lesson '+(number+1);
 return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="${esc(subtitle)}"><title>${esc(title)} · Lesson ${number} · AMG Life</title><link rel="icon" href="/course/assets/amg-mark.webp"><link rel="stylesheet" href="/course/shared/app.css"><link rel="stylesheet" href="/course/shared/lesson.css"><script src="lesson-data.js" defer></script>${foundation?'<script src="foundation.js" defer></script>':''}<script src="/course/shared/lesson.js" defer></script></head><body class="lesson-page">
<a class="skip" href="#main">Skip to lesson</a>${courseHeader('course')}
<div class="lesson-layout"><main id="main" class="lesson-main">
<div class="lesson-title"><p class="lesson-breadcrumb"><a href="/course/">My course</a><span aria-hidden="true">/</span>${esc(module)}</p><div class="lesson-title-row"><h1>${esc(title)}</h1><span class="lesson-duration">${durationLabel(duration)} <span>min</span></span></div><div class="lesson-meta"><span>Lesson ${number} of ${curriculum.length}</span><span>${questions} required questions</span></div></div>
<ol class="lesson-steps" aria-label="Lesson steps"><li id="step-watch" aria-current="step"><span class="step-number" aria-hidden="true">1</span><span>Watch lesson</span><span class="step-state" id="step-watch-state">In progress</span></li><li id="step-questions"><span class="step-number" aria-hidden="true">2</span><span>Answer questions</span><span class="step-state" id="step-questions-state">Up next</span></li></ol>
<section id="scenario" class="lesson-player" aria-label="Lesson video"><figure><video id="scenario-video" controls playsinline preload="metadata" aria-label="${esc(title)}"></video><div id="inline-captions" class="inline-captions" hidden><div class="inline-caption-controls"><span>English captions</span><button id="toggle-inline-captions" type="button" aria-pressed="true" aria-controls="inline-caption-text">Hide captions</button></div><p id="inline-caption-text" aria-live="off"></p></div><figcaption><span>Lesson ${id}</span><span>Narrated by ${esc(narrator)}</span></figcaption></figure><div id="video-error" hidden><p>The video could not load. Retry, or open the transcript below.</p><button id="retry-video" type="button">Retry video</button></div></section>
<section id="practice" class="lesson-actions" aria-label="Required lesson questions"><div><h2>Lesson questions</h2><p id="watch-status" role="status" class="watch-status"></p></div><button id="open-check" class="primary" type="button" disabled>Open lesson questions</button><noscript>Enable JavaScript for the video, questions and saved progress.</noscript></section>
<section id="finish" class="lesson-finish" aria-label="Lesson completion"><div class="result-box"><p id="result" aria-live="polite"></p><button id="complete" class="primary" type="button" disabled>Finish this lesson</button><p id="completion-status" role="status" tabindex="-1"></p><p id="next-lesson" hidden><a class="primary next-lesson-link" href="${next}">${nextLabel} <span aria-hidden="true">→</span></a></p><p id="next-locked">Finish the video or transcript and answer every required question correctly.</p><button id="restart" type="button" class="text-button">Start a fresh practice attempt</button></div></section>
<div class="lesson-reference"><div class="reference-heading"><h2>Lesson resources</h2><span>Optional reference</span></div><details class="reference-disclosure" id="transcript-disclosure"><summary><span>Full transcript</span><span class="disclosure-chevron" aria-hidden="true"></span></summary><div class="disclosure-content"><p id="transcript"></p><p class="fine">Prefer to read? Study the full transcript, then complete the same required questions.</p><button id="transcript-ready" type="button">I’ve read the lesson — open questions</button></div></details><details class="reference-disclosure" id="teaching-disclosure"><summary><span>Explanations & examples</span><span class="disclosure-chevron" aria-hidden="true"></span></summary><div class="disclosure-content">${referenceHtml}</div></details><details class="reference-disclosure" id="objectives-disclosure"><summary><span>Learning objectives</span><span class="disclosure-chevron" aria-hidden="true"></span></summary><div class="disclosure-content objectives">${objectivesHtml}</div></details><details class="reference-disclosure sources" id="sources-disclosure"><summary><span>Sources & exam topics</span><span class="disclosure-chevron" aria-hidden="true"></span></summary><div class="disclosure-content">${sourcesHtml}</div></details></div>
<nav class="lesson-bottom-nav" aria-label="Previous lesson and course home"><a href="${previous}">← ${number===1?'Course overview':'Previous lesson'}</a><a href="/course/">All lessons</a></nav>
</main>${courseRail(lesson)}</div>${courseFooter()}
<dialog id="lesson-check" class="check-dialog" aria-labelledby="check-heading" aria-describedby="check-description"><div class="check-top"><div><p class="eyebrow">LESSON ${number} · REQUIRED QUESTIONS</p><h2 id="check-heading" tabindex="-1">Lesson questions</h2></div><button id="close-check" type="button" aria-label="Close questions and return to lesson">Close <span aria-hidden="true">×</span></button></div><p id="check-description">Answer every question correctly. Review explanations and retry as needed.</p><p id="check-progress" class="fine" role="status"></p><div id="check-content" class="question"></div></dialog>
</body></html>\n`;
}
export function renderAuthoredReferences(lesson) {
 return lesson.blocks.map((block,index)=>`<section id="section-${index}" class="reference-section"><p class="eyebrow">${String(index+1).padStart(2,'0')}</p><h2>${esc(block.title)}</h2><p>${esc(block.narration)}</p><div class="concept-grid">${block.visual.items.map(([title,text])=>`<article class="simple-card"><h3>${esc(title)}</h3><p>${esc(text)}</p></article>`).join('')}</div></section>`).join('')+(lesson.notes.length?`<section class="reference-section"><h2>More detail</h2>${lesson.notes.map(note=>`<article class="teaching-note"><h3>${esc(note.title)}</h3><p>${esc(note.text)}</p><p><strong>Example:</strong> ${esc(note.example)}</p></article>`).join('')}</section>`:'');
}
